//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zadatak_1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwEmployee
    {
        public int UserId { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public string Email { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string Employee { get; set; }
        public int EmployeeId { get; set; }
        public string Citizenship { get; set; }
        public string Engagement { get; set; }
        public string Gender { get; set; }
        public int HotelFloor { get; set; }
        public Nullable<decimal> Salary { get; set; }
    }
}
